# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuel_proxy/proto/job_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuel_proxy/proto/job_config.proto',
  package='apollo.tools',
  syntax='proto2',
  serialized_pb=_b('\n/modules/tools/fuel_proxy/proto/job_config.proto\x12\x0c\x61pollo.tools\"\x99\x01\n\tBosConfig\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\naccess_key\x18\x02 \x01(\t\x12\x12\n\nsecret_key\x18\x03 \x01(\t\x12\x32\n\x06region\x18\x04 \x01(\x0e\x32\x1e.apollo.tools.BosConfig.Region:\x02\x62j\" \n\x06Region\x12\x06\n\x02\x62j\x10\x00\x12\x06\n\x02gz\x10\x01\x12\x06\n\x02su\x10\x02\"^\n\x0f\x41zureBlobConfig\x12\x17\n\x0fstorage_account\x18\x01 \x01(\t\x12\x1a\n\x12storage_access_key\x18\x02 \x01(\t\x12\x16\n\x0e\x62lob_container\x18\x03 \x01(\t\"r\n\x07Storage\x12&\n\x03\x62os\x18\x01 \x01(\x0b\x32\x17.apollo.tools.BosConfigH\x00\x12-\n\x04\x62lob\x18\x02 \x01(\x0b\x32\x1d.apollo.tools.AzureBlobConfigH\x00\x42\x10\n\x0estorage_config\"\xbd\x02\n\tJobConfig\x12\x31\n\x08job_type\x18\x01 \x01(\x0e\x32\x1f.apollo.tools.JobConfig.JobType\x12\x12\n\npartner_id\x18\x02 \x01(\t\x12&\n\x07storage\x18\x03 \x01(\x0b\x32\x15.apollo.tools.Storage\x12\x17\n\x0finput_data_path\x18\x04 \x01(\t\x12\x0f\n\x07zone_id\x18\x05 \x01(\r\x12\x12\n\nlidar_type\x18\x06 \x01(\t\x12!\n\x19output_trained_model_path\x18\x07 \x01(\t\"`\n\x07JobType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x17\n\x13VEHICLE_CALIBRATION\x10\x01\x12\x10\n\x0cSIMPLE_HDMAP\x10\x02\x12\x1d\n\x19PERCEPTION_MODEL_TRAINING\x10\x03')
)



_BOSCONFIG_REGION = _descriptor.EnumDescriptor(
  name='Region',
  full_name='apollo.tools.BosConfig.Region',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='bj', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gz', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='su', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_BOSCONFIG_REGION)

_JOBCONFIG_JOBTYPE = _descriptor.EnumDescriptor(
  name='JobType',
  full_name='apollo.tools.JobConfig.JobType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_CALIBRATION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMPLE_HDMAP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERCEPTION_MODEL_TRAINING', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=655,
  serialized_end=751,
)
_sym_db.RegisterEnumDescriptor(_JOBCONFIG_JOBTYPE)


_BOSCONFIG = _descriptor.Descriptor(
  name='BosConfig',
  full_name='apollo.tools.BosConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket', full_name='apollo.tools.BosConfig.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='access_key', full_name='apollo.tools.BosConfig.access_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secret_key', full_name='apollo.tools.BosConfig.secret_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='apollo.tools.BosConfig.region', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOSCONFIG_REGION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=219,
)


_AZUREBLOBCONFIG = _descriptor.Descriptor(
  name='AzureBlobConfig',
  full_name='apollo.tools.AzureBlobConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storage_account', full_name='apollo.tools.AzureBlobConfig.storage_account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='storage_access_key', full_name='apollo.tools.AzureBlobConfig.storage_access_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blob_container', full_name='apollo.tools.AzureBlobConfig.blob_container', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=315,
)


_STORAGE = _descriptor.Descriptor(
  name='Storage',
  full_name='apollo.tools.Storage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bos', full_name='apollo.tools.Storage.bos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blob', full_name='apollo.tools.Storage.blob', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='storage_config', full_name='apollo.tools.Storage.storage_config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=317,
  serialized_end=431,
)


_JOBCONFIG = _descriptor.Descriptor(
  name='JobConfig',
  full_name='apollo.tools.JobConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_type', full_name='apollo.tools.JobConfig.job_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partner_id', full_name='apollo.tools.JobConfig.partner_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='storage', full_name='apollo.tools.JobConfig.storage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_data_path', full_name='apollo.tools.JobConfig.input_data_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone_id', full_name='apollo.tools.JobConfig.zone_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lidar_type', full_name='apollo.tools.JobConfig.lidar_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_trained_model_path', full_name='apollo.tools.JobConfig.output_trained_model_path', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOBCONFIG_JOBTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=751,
)

_BOSCONFIG.fields_by_name['region'].enum_type = _BOSCONFIG_REGION
_BOSCONFIG_REGION.containing_type = _BOSCONFIG
_STORAGE.fields_by_name['bos'].message_type = _BOSCONFIG
_STORAGE.fields_by_name['blob'].message_type = _AZUREBLOBCONFIG
_STORAGE.oneofs_by_name['storage_config'].fields.append(
  _STORAGE.fields_by_name['bos'])
_STORAGE.fields_by_name['bos'].containing_oneof = _STORAGE.oneofs_by_name['storage_config']
_STORAGE.oneofs_by_name['storage_config'].fields.append(
  _STORAGE.fields_by_name['blob'])
_STORAGE.fields_by_name['blob'].containing_oneof = _STORAGE.oneofs_by_name['storage_config']
_JOBCONFIG.fields_by_name['job_type'].enum_type = _JOBCONFIG_JOBTYPE
_JOBCONFIG.fields_by_name['storage'].message_type = _STORAGE
_JOBCONFIG_JOBTYPE.containing_type = _JOBCONFIG
DESCRIPTOR.message_types_by_name['BosConfig'] = _BOSCONFIG
DESCRIPTOR.message_types_by_name['AzureBlobConfig'] = _AZUREBLOBCONFIG
DESCRIPTOR.message_types_by_name['Storage'] = _STORAGE
DESCRIPTOR.message_types_by_name['JobConfig'] = _JOBCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BosConfig = _reflection.GeneratedProtocolMessageType('BosConfig', (_message.Message,), dict(
  DESCRIPTOR = _BOSCONFIG,
  __module__ = 'modules.tools.fuel_proxy.proto.job_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.BosConfig)
  ))
_sym_db.RegisterMessage(BosConfig)

AzureBlobConfig = _reflection.GeneratedProtocolMessageType('AzureBlobConfig', (_message.Message,), dict(
  DESCRIPTOR = _AZUREBLOBCONFIG,
  __module__ = 'modules.tools.fuel_proxy.proto.job_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.AzureBlobConfig)
  ))
_sym_db.RegisterMessage(AzureBlobConfig)

Storage = _reflection.GeneratedProtocolMessageType('Storage', (_message.Message,), dict(
  DESCRIPTOR = _STORAGE,
  __module__ = 'modules.tools.fuel_proxy.proto.job_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.Storage)
  ))
_sym_db.RegisterMessage(Storage)

JobConfig = _reflection.GeneratedProtocolMessageType('JobConfig', (_message.Message,), dict(
  DESCRIPTOR = _JOBCONFIG,
  __module__ = 'modules.tools.fuel_proxy.proto.job_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.JobConfig)
  ))
_sym_db.RegisterMessage(JobConfig)


# @@protoc_insertion_point(module_scope)
